services:
  pipeline:
    build:
      context: ./Pipeline
    image: quantwise-pipeline:latest
    container_name: quantwise-pipeline
    restart: unless-stopped
    env_file:
      - ./Pipeline/.env
    environment:
      - YF_CACHE_DIR=/opt/yf-cache
    ports:
      - "8000:8000"          # .NET FetchDailyPipelineJob calls localhost:8000/api/score
    volumes:
      - yf_cache_pipeline:/opt/yf-cache
    networks:
      - project-network

  postgres:
    image: postgres:18
    container_name: postgres-project
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - project-network

  redis:
    image: redis:8-alpine
    container_name: redis-project
    ports:
      - "6500:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - project-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit-project
    ports:
      - "25:1025"
      - "8080:8025" 
    networks:
      - project-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-project
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - project-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq-project
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
      - project-network
    restart: unless-stopped


volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
  rabbitmq_data:
  yf_cache_pipeline:


networks:
  project-network:
    driver: bridge
