// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project.Modules.Recommendations.Infrastructure.Database;

#nullable disable

namespace Project.Modules.Recommendations.Infrastructure.Migrations
{
    [DbContext(typeof(RecommendationsDbContext))]
    [Migration("20260616184336_AddUserHoldings")]
    partial class AddUserHoldings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Recommendations")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedOnUtc", "OccurredOnUtc")
                        .HasDatabaseName("ix_inbox_messages_processed_on_utc_occurred_on_utc");

                    b.ToTable("inbox_messages", "Recommendations");
                });

            modelBuilder.Entity("Project.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "Recommendations");
                });

            modelBuilder.Entity("Project.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredOnUtc", "ProcessedOnUtc")
                        .HasDatabaseName("idx_outbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    b.ToTable("outbox_messages", "Recommendations");
                });

            modelBuilder.Entity("Project.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "Recommendations");
                });

            modelBuilder.Entity("Project.Modules.Recommendations.Domain.DailyRuns.DailyRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.HasKey("Id")
                        .HasName("pk_daily_runs");

                    b.HasIndex("GeneratedAt")
                        .HasDatabaseName("ix_daily_runs_generated_at");

                    b.ToTable("daily_runs", "Recommendations");
                });

            modelBuilder.Entity("Project.Modules.Recommendations.Domain.DailyRuns.StockPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Agreement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("agreement");

                    b.Property<double?>("AnalystRating")
                        .HasColumnType("double precision")
                        .HasColumnName("analyst_rating");

                    b.Property<double>("ChangePct")
                        .HasColumnType("double precision")
                        .HasColumnName("change_pct");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<double>("ConvictionScore")
                        .HasColumnType("double precision")
                        .HasColumnName("conviction_score");

                    b.Property<Guid>("DailyRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_run_id");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<double?>("NewsScore")
                        .HasColumnType("double precision")
                        .HasColumnName("news_score");

                    b.Property<double?>("PtUpsidePct")
                        .HasColumnType("double precision")
                        .HasColumnName("pt_upside_pct");

                    b.Property<string>("RatingLabel")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rating_label");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.PrimitiveCollection<string[]>("RiskFlags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("risk_flags");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("risk_level");

                    b.Property<double>("SentimentScore")
                        .HasColumnType("double precision")
                        .HasColumnName("sentiment_score");

                    b.Property<string>("Signal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("signal");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticker");

                    b.HasKey("Id")
                        .HasName("pk_stock_predictions");

                    b.HasIndex("DailyRunId")
                        .HasDatabaseName("ix_stock_predictions_daily_run_id");

                    b.HasIndex("RiskLevel")
                        .HasDatabaseName("ix_stock_predictions_risk_level");

                    b.HasIndex("Ticker")
                        .HasDatabaseName("ix_stock_predictions_ticker");

                    b.ToTable("stock_predictions", "Recommendations");
                });

            modelBuilder.Entity("Project.Modules.Recommendations.Domain.Holdings.UserHolding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AllocationPct")
                        .HasColumnType("double precision")
                        .HasColumnName("allocation_pct");

                    b.Property<DateTime>("RunGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_generated_at");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_holdings");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_holdings_user_id");

                    b.ToTable("user_holdings", "Recommendations");
                });

            modelBuilder.Entity("Project.Modules.Recommendations.Domain.DailyRuns.StockPrediction", b =>
                {
                    b.HasOne("Project.Modules.Recommendations.Domain.DailyRuns.DailyRun", null)
                        .WithMany("Predictions")
                        .HasForeignKey("DailyRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_predictions_daily_runs_daily_run_id");
                });

            modelBuilder.Entity("Project.Modules.Recommendations.Domain.DailyRuns.DailyRun", b =>
                {
                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
