// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project.Modules.Portfolio.Infrastructure.Database;

#nullable disable

namespace Project.Modules.Portfolio.Infrastructure.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260715225920_RetireLegacyPortfolio")]
    partial class RetireLegacyPortfolio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Portfolio")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedOnUtc", "OccurredOnUtc")
                        .HasDatabaseName("ix_inbox_messages_processed_on_utc_occurred_on_utc");

                    b.ToTable("inbox_messages", "Portfolio");
                });

            modelBuilder.Entity("Project.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "Portfolio");
                });

            modelBuilder.Entity("Project.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredOnUtc", "ProcessedOnUtc")
                        .HasDatabaseName("idx_outbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    b.ToTable("outbox_messages", "Portfolio");
                });

            modelBuilder.Entity("Project.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "Portfolio");
                });

            modelBuilder.Entity("Project.Modules.Portfolio.Domain.Goals.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("HorizonYears")
                        .HasColumnType("integer")
                        .HasColumnName("horizon_years");

                    b.Property<decimal>("InvestmentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("investment_amount");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_goals");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_goals_user_id");

                    b.ToTable("goals", "Portfolio");
                });

            modelBuilder.Entity("Project.Modules.Portfolio.Domain.Goals.InvestorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EffectiveRisk")
                        .HasColumnType("integer")
                        .HasColumnName("effective_risk");

                    b.Property<string>("Engagement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("engagement");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<Guid>("QuestionnaireResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("questionnaire_response_id");

                    b.Property<string>("RiskBand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_band");

                    b.Property<string>("ScoringVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scoring_version");

                    b.Property<bool>("SpeculativeUnlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("speculative_unlocked");

                    b.Property<int>("Tolerance")
                        .HasColumnType("integer")
                        .HasColumnName("tolerance");

                    b.Property<string>("UsdComfort")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("usd_comfort");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_investor_profiles");

                    b.HasIndex("QuestionnaireResponseId")
                        .HasDatabaseName("ix_investor_profiles_questionnaire_response_id");

                    b.HasIndex("GoalId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_investor_profiles_goal_id_version");

                    b.ToTable("investor_profiles", "Portfolio");
                });

            modelBuilder.Entity("Project.Modules.Portfolio.Domain.Goals.QuestionnaireResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answers_json");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<string>("ScoringVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scoring_version");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("pk_questionnaire_responses");

                    b.HasIndex("GoalId")
                        .HasDatabaseName("ix_questionnaire_responses_goal_id");

                    b.ToTable("questionnaire_responses", "Portfolio");
                });

            modelBuilder.Entity("Project.Modules.Portfolio.Domain.Instruments.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("asset_class");

                    b.Property<double?>("AvgDailyValueTraded")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_daily_value_traded");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<double?>("LastClose")
                        .HasColumnType("double precision")
                        .HasColumnName("last_close");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("market");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<double?>("RealizedVol1Y")
                        .HasColumnType("double precision")
                        .HasColumnName("realized_vol1y");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sector");

                    b.Property<DateTime?>("StatsAsOf")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stats_as_of");

                    b.PrimitiveCollection<List<string>>("SuitableFor")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("suitable_for");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_instruments");

                    b.HasIndex("Market", "Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_instruments_market_symbol");

                    b.ToTable("instruments", "Portfolio");
                });

            modelBuilder.Entity("Project.Modules.Portfolio.Domain.Portfolios.GoalPortfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<bool>("DrawdownAlertActive")
                        .HasColumnType("boolean")
                        .HasColumnName("drawdown_alert_active");

                    b.Property<double>("DrawdownThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("drawdown_threshold");

                    b.Property<bool>("DriftAlertActive")
                        .HasColumnType("boolean")
                        .HasColumnName("drift_alert_active");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<double>("HighWaterMarkNav")
                        .HasColumnType("double precision")
                        .HasColumnName("high_water_mark_nav");

                    b.Property<DateTime>("InceptionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inception_date");

                    b.Property<DateTime?>("LastDigestAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_digest_at");

                    b.Property<double>("LastNav")
                        .HasColumnType("double precision")
                        .HasColumnName("last_nav");

                    b.Property<DateTime?>("LastValuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_valued_at");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_goal_portfolios");

                    b.HasIndex("GoalId", "Status")
                        .HasDatabaseName("ix_goal_portfolios_goal_id_status");

                    b.ToTable("goal_portfolios", "Portfolio");
                });

            modelBuilder.Entity("Project.Modules.Portfolio.Domain.Portfolios.PortfolioHolding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("EntryPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("entry_price");

                    b.Property<Guid>("GoalPortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_portfolio_id");

                    b.Property<double>("Shares")
                        .HasColumnType("double precision")
                        .HasColumnName("shares");

                    b.Property<string>("Sleeve")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sleeve");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<double>("TargetWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("target_weight");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_holding");

                    b.HasIndex("GoalPortfolioId")
                        .HasDatabaseName("ix_portfolio_holding_goal_portfolio_id");

                    b.ToTable("portfolio_holding", "Portfolio");
                });

            modelBuilder.Entity("Project.Modules.Portfolio.Domain.Proposals.PortfolioProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("AssumptionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("assumptions_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("DrawdownAlertPct")
                        .HasColumnType("double precision")
                        .HasColumnName("drawdown_alert_pct");

                    b.Property<int>("EffectiveRisk")
                        .HasColumnType("integer")
                        .HasColumnName("effective_risk");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<string>("InputsHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("inputs_hash");

                    b.Property<string>("PositionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("positions_json");

                    b.Property<string>("RebalanceCadence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rebalance_cadence");

                    b.Property<string>("RiskBand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_band");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("template_key");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_name");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_proposals");

                    b.HasIndex("GoalId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_portfolio_proposals_goal_id_version");

                    b.ToTable("portfolio_proposals", "Portfolio");
                });

            modelBuilder.Entity("Project.Modules.Portfolio.Domain.Strategies.StrategyTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BucketsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("buckets_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("DrawdownAlertPct")
                        .HasColumnType("double precision")
                        .HasColumnName("drawdown_alert_pct");

                    b.PrimitiveCollection<List<string>>("GoalTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("goal_types");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RebalanceCadence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rebalance_cadence");

                    b.Property<bool>("RequiresSpeculativeUnlock")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_speculative_unlock");

                    b.Property<int>("RiskMax")
                        .HasColumnType("integer")
                        .HasColumnName("risk_max");

                    b.Property<int>("RiskMin")
                        .HasColumnType("integer")
                        .HasColumnName("risk_min");

                    b.HasKey("Id")
                        .HasName("pk_strategy_templates");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_strategy_templates_key");

                    b.ToTable("strategy_templates", "Portfolio");
                });

            modelBuilder.Entity("Project.Modules.Portfolio.Domain.Goals.InvestorProfile", b =>
                {
                    b.HasOne("Project.Modules.Portfolio.Domain.Goals.Goal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_investor_profiles_goals_goal_id");

                    b.HasOne("Project.Modules.Portfolio.Domain.Goals.QuestionnaireResponse", null)
                        .WithMany()
                        .HasForeignKey("QuestionnaireResponseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_investor_profiles_questionnaire_responses_questionnaire_res");
                });

            modelBuilder.Entity("Project.Modules.Portfolio.Domain.Goals.QuestionnaireResponse", b =>
                {
                    b.HasOne("Project.Modules.Portfolio.Domain.Goals.Goal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionnaire_responses_goals_goal_id");
                });

            modelBuilder.Entity("Project.Modules.Portfolio.Domain.Portfolios.PortfolioHolding", b =>
                {
                    b.HasOne("Project.Modules.Portfolio.Domain.Portfolios.GoalPortfolio", null)
                        .WithMany("Holdings")
                        .HasForeignKey("GoalPortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_holding_goal_portfolios_goal_portfolio_id");
                });

            modelBuilder.Entity("Project.Modules.Portfolio.Domain.Proposals.PortfolioProposal", b =>
                {
                    b.HasOne("Project.Modules.Portfolio.Domain.Goals.Goal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_proposals_goals_goal_id");
                });

            modelBuilder.Entity("Project.Modules.Portfolio.Domain.Portfolios.GoalPortfolio", b =>
                {
                    b.Navigation("Holdings");
                });
#pragma warning restore 612, 618
        }
    }
}
